
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    test: liveness
  name: liveness-exec               #myapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1-pod

      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1-container
        image: stacksimplify/kubenginx:1.0.0
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

